FROM alpine:latest
RUN apk add -U --no-cache python3 python3-dev py3-pip tzdata git gcc libc-dev musl-dev linux-headers jpeg-dev zlib-dev && \
    git clone --depth=1 https://github.com/txperl/PixivBiu.git && \
    mkdir Pixiv && \
    mkdir /PixivBiu/.pkg/code && \
    mkdir /PixivBiu/.pkg/public && \
    cp -r /PixivBiu/altfe/                        /PixivBiu/.pkg/code/altfe/ && \
    cp -r /PixivBiu/app/                          /PixivBiu/.pkg/code/app/ && \
    cp /PixivBiu/main.py                          /PixivBiu/.pkg/code/ && \
    cp -r /PixivBiu/usr/                          /PixivBiu/.pkg/public/usr/ && \
    cp /PixivBiu/app/config/biu_default.yml       /PixivBiu/.pkg/public/config.yml && \
    cp /PixivBiu/LICENSE                          /PixivBiu/.pkg/public/ && \
    cp /PixivBiu/README.md                        /PixivBiu/.pkg/public/ && \
    pip install -r /PixivBiu/requirements.txt --no-cache-dir && \
    pip install pyinstaller --no-cache-dir && \
    python3 /PixivBiu/.pkg/py-pkger.py auto && \
    mv /PixivBiu/.pkg/dist/* /Pixiv  && \
    rm -rf PixivBiu/ && \
    rm /Pixiv/config.yml && \
    rm /Pixiv/LICENSE && \
    rm /Pixiv/README.md && \
    apk del python3 python3-dev py3-pip tzdata git gcc libc-dev musl-dev linux-headers jpeg-dev zlib-dev && \
    rm -rf /var/cache/apk/* && \
    rm -rf /root/.cache && \
    rm -rf /tmp/* 
EXPOSE 4001
ENV sys.host="0.0.0.0:4001" \
    sys.debug="false" \
    sys.api="public" \
    sys.proxy="" \
    sys.language="" \
    sys.theme="multiverse" \
    sys.autoOpen="true" \
    biu.search.maxThreads 8 \
    biu.search.loadCacheFirst="true" \
    biu.download.mode="dl-single" \
    biu.download.aria2Host="localhost:6800" \
    biu.download.aria2Secret="" \
    biu.download.maxDownloading 8 \
    biu.download.saveURI="{ROOTPATH}/downloads/{KT}/" \
    biu.download.saveFileName="{title}_{work_id}" \
    biu.download.autoArchive="true" \
    biu.download.autoDeterTheSame="true" \
    biu.download.whatsUgoira="webp" \
    biu.download.imageHost=""
ENTRYPOINT ["/Pixiv/main"]
